steps:
  # 소스 코드 가져오기 및 준비
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/fireintheall/winder2.git', 'src']

  # 도커 이미지 빌드 (Dockerfile 위치 지정)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/discord-bot:latest', '-f', 'src/KoreanDiscordAssistant/Dockerfile', 'src/KoreanDiscordAssistant']
  
  # 이미지를 Container Registry에 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/discord-bot:latest']
  
  # Cloud Run에 배포
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'discord-schedule-bot'
      - '--image=gcr.io/$PROJECT_ID/discord-bot:latest'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--memory=512Mi'
      - '--set-env-vars=DISCORD_TOKEN=${_DISCORD_TOKEN}'
      - '--set-env-vars=BOT_PREFIX=${_BOT_PREFIX}'
      - '--set-env-vars=DEBUG=${_DEBUG}'
      - '--port=8080'

# 이미지가 Container Registry에 저장됨
images:
  - 'gcr.io/$PROJECT_ID/discord-bot:latest'

# 치환 변수 (환경 변수)
substitutions:
  _DISCORD_TOKEN: '' # deploy-to-gcp.sh 스크립트에서 제공
  _BOT_PREFIX: '!'
  _DEBUG: 'False'

timeout: 1800s
