version: '3'
services:
  discord-bot:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - BOT_PREFIX=${BOT_PREFIX:-!}
      - DEBUG=${DEBUG:-False}
    restart: always
    volumes:
      - ./logs:/app/logs
